Repository GoogleCloudPlatform/getting-started-java, pull requests merged in 2020-06, with the labels that each got.

#670 move Helloworld-servlet sample to java-docs-samples
  helloworld-servlet/README.md
  helloworld-servlet/build.gradle
  helloworld-servlet/gradle/wrapper/gradle-wrapper.jar
  helloworld-servlet/gradle/wrapper/gradle-wrapper.properties
  helloworld-servlet/gradlew
  helloworld-servlet/gradlew.bat
  helloworld-servlet/pom.xml
  helloworld-servlet/src/main/appengine/app.yaml
  helloworld-servlet/src/main/java/com/example/appengine/gettingstartedjava/helloworld/HelloServlet.java
Labels: cla: yes

#671 Remove flexible/tomcat sample
  flexible/tomcat/helloworld/README.md
  flexible/tomcat/helloworld/build.gradle
  flexible/tomcat/helloworld/gradle/wrapper/gradle-wrapper.jar
  flexible/tomcat/helloworld/gradle/wrapper/gradle-wrapper.properties
  flexible/tomcat/helloworld/gradlew
  flexible/tomcat/helloworld/gradlew.bat
  flexible/tomcat/helloworld/pom.xml
  flexible/tomcat/helloworld/src/main/appengine/app.yaml
  flexible/tomcat/helloworld/src/main/java/com/example/appengine/gettingstartedjava/helloworld/HelloServlet.java
  pom.xml
Labels: cla: yes

#675 Remove deleted modules from parent pom.xml.
  pom.xml
Labels: cla: yes

#678 Update appengine-web.xml
  appengine-standard-java8/helloworld-gae-javasdk-tools/src/main/webapp/WEB-INF/appengine-web.xml
Labels: cla: yes

#682 Update kokoro config to match java-docs-samples.
  .kokoro/java11/common.cfg
  .kokoro/java11/continuous.cfg
  .kokoro/java11/periodic.cfg
  .kokoro/java11/presubmit.cfg
  .kokoro/java8/common.cfg
  .kokoro/java8/continuous.cfg
  .kokoro/java8/periodic.cfg
  .kokoro/java8/presubmit.cfg
  .kokoro/lint/common.cfg
  .kokoro/lint/presubmit.cfg
  .kokoro/static_analysis/common.cfg
  .kokoro/static_analysis/presubmit.cfg
  .kokoro/tests/diff_tests.sh
  .kokoro/tests/run_diff_only.sh
  .kokoro/tests/run_lint.sh
  .kokoro/tests/run_static_analysis.sh
  .kokoro/tests/run_tests.sh
  pom.xml
Labels: cla: yes, do not merge

#689 Fixed leaf pom.xml files
  appengine-standard-java8/helloworld-gae-javasdk-tools/pom.xml
  appengine-standard-java8/kotlin-appengine-standard/pom.xml
  appengine-standard-java8/kotlin-sb-appengine-standard/pom.xml
  appengine-standard-java8/kotlin-spark-appengine-standard/pom.xml
  background/pom.xml
  bookshelf-standard/2-structured-data/pom.xml
  bookshelf-standard/2-structured-data/src/test/java/com/example/getstarted/basicactions/UserJourneyTestIT.java
  bookshelf-standard/3-binary-data/pom.xml
  bookshelf-standard/3-binary-data/src/test/java/com/example/getstarted/basicactions/UserJourneyTestIT.java
  bookshelf-standard/3-binary-data/src/test/resources/com/example/getstarted/basicactions/appengine.png
  bookshelf-standard/4-auth/pom.xml
  bookshelf-standard/4-auth/src/test/java/com/example/getstarted/basicactions/UserJourneyTestIT.java
  bookshelf-standard/5-logging/pom.xml
  bookshelf-standard/5-logging/src/test/java/com/example/getstarted/basicactions/UserJourneyTestIT.java
  bookshelf-standard/pom.xml
  bookshelf/1-cloud-run/pom.xml
  bookshelf/1-cloud-run/src/test/java/com/example/getstarted/basicactions/UserJourneyTestIT.java
  bookshelf/2-structured-data/pom.xml
  bookshelf/2-structured-data/src/test/java/com/example/getstarted/basicactions/UserJourneyTestIT.java
  bookshelf/3-binary-data/pom.xml
  bookshelf/3-binary-data/src/test/java/com/example/getstarted/basicactions/UserJourneyTestIT.java
  bookshelf/3-binary-data/src/test/resources/com/example/getstarted/basicactions/appengine.png
  bookshelf/4-auth/pom.xml
  bookshelf/4-auth/src/test/java/com/example/getstarted/basicactions/UserJourneyTestIT.java
  bookshelf/5-logging/pom.xml
  bookshelf/5-logging/src/test/java/com/example/getstarted/basicactions/UserJourneyTestIT.java
  bookshelf/pom.xml
  gce/pom.xml
  helloworld-jsp/pom.xml
  pom.xml
Labels: cla: yes

#695 Update appengine plugin version
  appengine-standard-java8/helloworld-gae-javasdk-tools/README.md
  appengine-standard-java8/helloworld-gae-javasdk-tools/pom.xml
  appengine-standard-java8/kotlin-appengine-standard/README.md
  appengine-standard-java8/kotlin-sb-appengine-standard/README.md
  appengine-standard-java8/kotlin-spark-appengine-standard/README.md
  bookshelf-standard/2-structured-data/README.md
  bookshelf-standard/3-binary-data/README.md
  bookshelf-standard/4-auth/README.md
  bookshelf-standard/5-logging/README.md
  bookshelf/2-structured-data/README.md
  bookshelf/3-binary-data/README.md
  bookshelf/4-auth/README.md
  bookshelf/5-logging/README.md
  helloworld-jsp/README.md
  helloworld-jsp/build.gradle
  helloworld-jsp/pom.xml
Labels: cla: yes

#700 Remove Noah
  .github/blunderbuss.yml
Labels: automerge, cla: yes
